---
  - name: restart_demon 
    service:
           name: deamon-reload
    become: true

  - name:  restart_docker
    service:
        name: docker
        state: restarted
    become: true          
# handlers file for kube