---
# tasks file for kube
  - include_tasks: "{{ansible_distribution}}.yml" 
    when: inventory_hostname in groups['kube_cluster'] 

  - include_tasks: "master.yml"
    when: inventory_hostname in groups['master']

  - include_tasks: "slave.yml"
    when: inventory_hostname in groups['slave']    
        
