    # - name: initialize the cluster
    #   shell: kubeadm init 
    #   args:
    #     chdir: $HOME
    #     creates: cluster_initialized.txt
    #   become: true  
      
    # - name: create .kube directory
    #   file:
    #     path: $HOME/.kube
    #     state: directory
    #     mode: 0755

    # - name: copies admin.conf to user's kube config
    #   copy:
    #     src: /etc/kubernetes/admin.conf
    #     dest: /home/ubuntu/.kube/config
    #     remote_src: yes
    #   become: true 

    # - name: install Pod network
    #   shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
              
        
    - name: Get the token for joining the worker nodes
      become: true
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    # - name: Set join command as fact
    #   set_fact:
    #    join_command: "{{ kubernetes_join_command.stdout_lines[0] }}"
 


    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/home/opsree/kubernetes_join_command" mode=0777
      