---
  - name: update
    shell:  apt update 
    become: yes
    register: output

  - debug:
       var: output 
  
  - name: turn off swap
    shell: |
               swapoff -a && sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    become: yes

  - name: Install package
    apt: 
       name: "{{packages}}"    
       state: present
    become: yes  

  - name: get gpg key
    shell:  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes  -o /usr/share/keyrings/docker-archive-keyring.gpg
    register: output

  - debug:
      var: output    

  - name:  add repositry in apt
    blockinfile:
         dest: /etc/apt/sources.list.d/docker.list
         create: yes
         content: | 
                     deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable
    become: yes


  - name: update
    command: 
          cmd: apt-get update
    become: yes
    tags:
      - test 

  - name: install
    apt: 
        name: "{{docker}}"
        state: present 
    become: yes 


  - name: get gpg key
    shell:  curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    become: yes 

  - name:  add repositry in apt
    blockinfile:
         dest: /etc/apt/sources.list.d/kubernetes.list
         create: yes
         content: | 
                     deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main 
    become: yes

  - name: update
    command: 
          cmd: apt-get update
    become: yes
    tags:
      - test 

  - name: install
    apt: 
        name: "{{packages2}}"
        state: present 
    become: yes 

  - name: copying file with playbook
    become: true 
    copy:
        src: ~/Downloads/daemon.json
        dest: /etc/docker/daemon.json
        owner: ubuntu
        group: ubuntu        
        mode: 0644
        remote_src: no  
    notify:
         - restart_demon
         - restart_docker  

