---
  - name: update
    shell:  apt update 
    become: true
    register: output

  - debug:
       var: output 
  
  - name: turn off swap
    shell: |
               swapoff -a && sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    become: true

  - name: Install package
    apt: 
       name: "{{packages}}"    
       state: present
    become: true  

  - name: get gpg key
    shell: sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes  -o /usr/share/keyrings/docker-archive-keyring.gpg
    register: output

  - debug:
      var: output    

  - name:  add repositry in apt
    blockinfile:
         dest: /etc/apt/sources.list.d/docker.list
         create: yes
         content: | 
                     deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable
    become: true


  - name: update
    command: 
          cmd: apt-get update
    become: true
    tags:
      - test 

  - name: install
    apt: 
        name: "{{docker}}"
        state: present 
    become: true 


  - name: get gpg key
    shell:  curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    become: true

  - name:  add repositry in apt
    blockinfile:
         dest: /etc/apt/sources.list.d/kubernetes.list
         create: yes
         content: | 
                     deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main 
    become: true

  - name: update
    command: 
          cmd: apt-get update
    become: true
    tags:
      - test 

  - name: install
    apt: 
        name: "{{packages2}}"
        state: present 
    become: true 

  - name: copying file with playbook
    become: true 
    copy:
        src: ~/Downloads/json/daemon.json
        dest: /etc/docker/daemon.json
        owner: ubuntu
        group: ubuntu        
        mode: 0644
        remote_src: no  
    # notify:
    #      - restart_demon
    #      - restart_docker  

  - name: Delete config.yml from containerd 
    file:
       path: /etc/containerd/config.toml
       state: absent
    become: true

  
  - name: restart_demon 
    service:
           name: deamon-reload
    become: true

  - name:  restart_docker
    service:
        name: docker
        state: restarted
    become: true   

  - name:  restart_containerd
    service:
        name: containerd
        state: restarted
    become: true   

